name: Snap

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: canonical/action-build@v1.3.0
        id: snapcraft

      - name: Test installed snap
        run: |
          sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
          test "$(/snap/bin/envbool --print --value yes)" = true
          test "$(/snap/bin/envbool --print --value no)" = false
          test "$(DEBUG=on /snap/bin/envbool --print DEBUG)" = true

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: envbool-${{ runner.arch }}
          path: ${{ steps.snapcraft.outputs.snap }}

